name: CLA checker

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

permissions:
  statuses: write
  pull-requests: write
  contents: read

jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run cla-bot
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SIGNERS_PATH: cla-signers.txt
          GOOGLE_SHEET_URL: "https://docs.google.com/spreadsheets/d/1A7epcYPGAsYNcUfD3qcWpyHQjLQgUJkPlcQr7Y-4e3E/export?format=csv&gid=1088589458"
        run: |
          go run github.com/prequel-dev/clabot/cmd@v0.0.1
